// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMoroni.Models;

namespace ProjectMoroni.Migrations
{
    [DbContext(typeof(ScriptureNoteContext))]
    partial class ScriptureNoteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27");

            modelBuilder.Entity("ProjectMoroni.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Scripture"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "General Conference Talk"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Article"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("ProjectMoroni.Models.ScriptureNote", b =>
                {
                    b.Property<int>("ScriptureNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScriptureNoteId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ScriptureNotes");

                    b.HasData(
                        new
                        {
                            ScriptureNoteId = 1,
                            CategoryId = 1,
                            Link = "https://www.churchofjesuschrist.org/study/scriptures/bofm/alma/48?lang=eng&id=p17#p17",
                            Notes = "How can I be more like Moroni?",
                            Quote = "Yea, verily, verily I say unto you, if all men had been, and were, and ever would be, like unto Moroni, behold, the very powers of hell would have been shaken forever; yea, the devil would never have power over the hearts of the children of men.",
                            Reference = "Alma 48:17"
                        },
                        new
                        {
                            ScriptureNoteId = 2,
                            CategoryId = 1,
                            Link = "https://www.churchofjesuschrist.org/study/scriptures/bofm/alma/48?lang=eng&id=p17#p17",
                            Notes = "How can I be more like Moroni?",
                            Quote = "Yea, verily, verily I say unto you, if all men had been, and were, and ever would be, like unto Moroni, behold, the very powers of hell would have been shaken forever; yea, the devil would never have power over the hearts of the children of men.",
                            Reference = "Alma 48:17"
                        },
                        new
                        {
                            ScriptureNoteId = 3,
                            CategoryId = 1,
                            Link = "https://www.churchofjesuschrist.org/study/scriptures/bofm/alma/48?lang=eng&id=p17#p17",
                            Notes = "How can I be more like Moroni?",
                            Quote = "Yea, verily, verily I say unto you, if all men had been, and were, and ever would be, like unto Moroni, behold, the very powers of hell would have been shaken forever; yea, the devil would never have power over the hearts of the children of men.",
                            Reference = "Alma 48:17"
                        });
                });

            modelBuilder.Entity("ProjectMoroni.Models.ScriptureNote", b =>
                {
                    b.HasOne("ProjectMoroni.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
